poll/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [

    path('', include('pollsApp.urls')),
    path('admin/', admin.site.urls)
]

pollsApp/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('forms/', views.formsubmit, name='formsubmit'),
    path('customers/', views.displayCustomer, name='displayCustomer'),
]

pollsApp/models.py
import datetime

from django.utils import timezone
from django.db import models


class Question(models.Model):
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=1))

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    def __str__(self):
        return self.choice_text

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)


class Customer(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50, unique=True)
    contact = models.CharField(max_length=50, unique=True)
    # description= models.CharField(max_length=10)

pollsApp/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse

from .models import Question, Choice, Customer

from django.template import loader




def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/details.html', {'question': question})


def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def formsubmit(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        selectedata = Customer()
        selectedata.name = request.POST['name']
        selectedata.email = request.POST['email']
        selectedata.contact = request.POST['contact']
        try:
            selectedata.save()
        except Exception:
            messages.info(request, 'You\'ll be contacted shortly')
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('polls:index'))


def displayCustomer(request):
    customer = Customer.objects.all()
    context = {'customer': customer}
    return render(request, 'polls/forms.html', context)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

pollsApp/templates/polls/details.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

pollsApp/templates/polls/forms.html
{% if customer %}
    <ul>
    {% for question in customer %}
        <li>{{ customer.name }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Users are available.</p>
{% endif %}

pollsApp/templates/polls/index.html
<html>
<head>
<title>Cross Apps</title>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
</head>
<body>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'polls/font-awesome.min.css' %}">

<header>
    <div id="logo">
        {% load static %}
        <a href="#">
        <img src="{% static 'polls/images/logo.png' %}" alt="logo" width="50" height="50" >
        </a>
    </div>
    <nav id="main-nav">
        <i class="fa fa-bars" aria-hidden="true"></i>
        <ul>
            <a class="active" href="#home"> <li> Home</li></a>
            <a href="#about"><li>Webpulse</li></a>
            <a href="#pathprahari"><li>Pathprahari</li></a>
            <a href="#contact"><li>Contact</li></a>
        </ul>
    </nav>
</header>

<section id="home">
    <hr>
    <h1>Cross Apps</h1>
    <h2>Android App Development</h2>
</section>

<section id="about">
    <hr>
<div id="content">
    <h1>Webpulse Crm</h1>
    <h2>This App is designed with focus to help employees manage customer relationship better.</h2>
</div>

<div id="image">
      <img src="{%static 'polls/images/crm_resize.png'%}" alt="Cover">
</div>


</section>

<!--<section id="pathprahari">-->
    <!--<hr>-->
<!--<div id="pathprahariContent">-->
    <!--<h1>Pathprahari</h1>-->
    <!--<h2>Sick of traffic rule violaters, Uncleanliness? Join today to raise your voice.</h2>-->
<!--</div>-->

<!--<div id="pathprahariImage">-->
      <!--<img src="{%static 'polls/images/ss_resize.png'%}" alt="Cover" >-->
<!--</div>-->


<!--</section>-->
<section id="contact">
    <h3>Contact</h3>
    <hr>

    <form action="{% url 'polls:formsubmit'%} " method="post">
        {% csrf_token %}
        <input class="input_text" type="text" tabindex="1" placeholder="Name" name = "name" required><br>
        <input class="input_text" type="text" tabindex="2" placeholder="Contact" name = "contact" required><br>
        <input class="input_text" type="email" tabindex="3" placeholder="Email" name = "email" required><br>
        <input class="button" type="submit">
    </form>

{% if messages %}
<ul class="messages" >
    {% for message in messages %}
    <li style="font-size:40px;font-family:'Roboto',sans-serif; font-weight:500; color:#494949;">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

</section>

<footer>
    <p>&copy 2019 Cross Apps</p>
</footer>

<script src="http://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<script
src="{% static 'polls/mobile-menu.js' %}"
></script>
</body>
</html>


<!--<html>-->
<!--<head>-->
<!--<title>Portfolio</title>-->
<!--</head>-->
<!--<body>-->


<!--{% load static %}-->
<!--<link rel="stylesheet" type="text/css" href="{% static 'polls/stylesheet.css' %}">-->

<!--{% if latest_question_list %}-->
    <!--<ul>-->
    <!--{% for question in latest_question_list %}-->
        <!--<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>-->
    <!--{% endfor %}-->
    <!--</ul>-->
<!--{% else %}-->
    <!--<p>No polls are available.</p>-->
<!--{% endif %}-->

<!--</body>-->
<!--</html>-->

pollsApp/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>